name: Basic Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Clean Install
      run: npm ci

    - name: Run Tests
      run: npm test  # This runs your test script defined in package.json

    - name: Run a Simple Check (optional)
      run: node -e "console.log('Server check successful!')"
