name: Basic Node.js CI with Test Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests with Coverage
      run: npm test  # This will run the tests with nyc coverage reporting

    - name: Upload Coverage Report to GitHub (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/lcov-report/  # Path to the lcov report folder


    - name: Run a Simple Check (Optional)
      run: node -e "console.log('Server check successful!')"
