name: Basic Node.js CI with Test Coverage and Minimum Coverage Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Create coverage output directory
      run: mkdir -p .nyc_output

    - name: Run Tests with Coverage
      run: npm test  # This should run with nyc and generate coverage report

    - name: Enforce Minimum Coverage Threshold
      run: npx nyc --check-coverage --branches 80 --functions 80 --lines 80 --statements 80 npm test

    - name: Upload Coverage Report to GitHub (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/lcov-report/

    - name: Run a Simple Check (Optional)
      run: node -e "console.log('Server check successful!')"
