name: Basic Node.js CI with Test Coverage and Minimum Coverage Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checkout repository

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Setup Node.js
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests with Coverage
      run: npm test  # Run tests, which will generate a coverage report

    - name: Enforce Minimum Coverage Threshold
      run: npx nyc report --reporter=text-lcov | tee coverage/lcov-report/lcov-report.txt | npx coveralls

    - name: Upload Coverage Report to GitHub (Optional)
      uses: actions/upload-artifact@v4  # Upload coverage artifact
      with:
        name: coverage-report
        path: coverage/lcov-report/

    - name: Run a Simple Check (Optional)
      run: node -e "console.log('Server check successful!')"
